name: myapp

description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  url_launcher: ^6.2.5
  android_intent_plus: ^4.0.3
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.5.3
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  provider: ^6.1.2
  google_fonts: ^6.1.0
  flutter_rating_bar: ^4.0.1
  http: ^1.2.0
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  lottie: ^3.0.0
  avatar_glow: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/frames/
    - assets/animations/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
